---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: bazzite-opengamepadui
description: This is my personal OS image.
base-image: ghcr.io/ublue-os/bazzite-deck
image-version: stable-42

modules:
  - type: script
    scripts:
      - opengamepadui-session.sh

  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    install:
      packages:
        - https://github.com/ShadowBlip/OpenGamepadUI/releases/download/v0.40.3/opengamepadui-0.40.3-1.x86_64.rpm

  - type: signing
